[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]
cmds = ["npm install -g pnpm@8.15.1"]

[phases.install]
cmds = ["pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = ["npx prisma generate --schema=apps/backend/prisma/schema.prisma && cd apps/backend && npx nest build"]

[start]
cmd = "cd apps/backend && npx prisma migrate deploy && node dist/main"
