[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]
cmds = ["npm install -g pnpm@8.15.1"]

[phases.install]
cmds = ["pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = ["sh -c 'cd apps/backend && npx prisma generate && npx nest build'"]

[start]
cmd = "sh -c 'cd apps/backend && npx prisma migrate deploy && node dist/main'"
