[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]
cmds = ["npm install -g pnpm@8.15.1"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile || pnpm install"]

[phases.build]
cmds = ["pnpm prisma generate", "pnpm build"]

[start]
cmd = "pnpm prisma migrate deploy && node dist/main"
